### ISSUE TITLE
Add bundle analyzer

### ISSUE THREAD

**Issue by arrlancore** [kafinsalim/component-library#2]
We need this to know the size after each build.

**Comment by kfnx** [comment]
I see there is `npm run bundle-size` available in package.json, but not sure is it enough/represent real size because the value returned from the script and what it shows in explorer seems different

<img width="475" alt="Screenshot 2020-10-14 at 00 15 37" src="https://user-images.githubusercontent.com/33047308/95893839-6da80600-0db2-11eb-8092-6b4845df447e.png">

I try a quick googling and found this one https://github.com/ritz078/rollup-plugin-filesize, I'm not trying it yet

**Comment by arrlancore** [comment]
yeah I think rollup has its own, webpack has https://www.npmjs.com/package/webpack-bundle-analyzer

**Comment by kfnx** [comment]
will we change our bundler with webpack? I'm ok tho, I'm only using webpack but also not too expert in any of those bundlers

**Comment by arrlancore** [comment]
I think no need, rollup also have https://www.npmjs.com/package/rollup-plugin-visualizer

and they also able for threeshake

what is other thing we need to consider to change to wp ?

**Comment by kfnx** [comment]
I'm not sure, how is the typescript implementation and test? is it going smooth with rollup? if good then I think we have all we need for now.

Also, I just realized rollup is created by Rich Harris creator of svelte and also used internally by svelte. So maybe this could be a good chance to get an experience of using rollup and see how it works

**Comment by arrlancore** [comment]
#5 added
